sudo: false
language: node_js
node_js:
  - "stable"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
env:
  global:
    - secure: VgYj3w6ztd5rU+XLGLUNYkqjv/GXxyYAuAzNbFhMzYARMF/Kxc6Znwh9RkmNuQjVhRE5ViWEX8Gb0GqFqcHf5jpOjC7DkrkZ0pppWkUqaMhh+IQiU9mqWRxSVLRme1NMSlnRTv6NKX8ezHHmXy/OpuMHyfUoWbVJErXjtkwZw/M=
    - secure: SJrx53jlcIJpvWQFrxFHwNkVhanXNZo9LRZe39NCuRPjuhojkfpizRmD+ar/Ok1E6fA+FynSZEDOhahLLNgwFlUTOxtZ0RcRjAzaCQqaQN2u5keWe4DEh/7r6Db2rriuqRNcYpvKgZpAaGYLVunsMT8I21uClTXFxvABJ6GRFls=
addons:
  sauce_connect: true

before_script:
  - ./server/server.js &
  - sleep 2
